sudo: false
branches:
  only:
    - develop
language: elixir
elixir:
  - 1.3.1
otp_release:
  - 18.0
before_script:
  - mix dialyzer.plt 
script:
  - mix credo
  - mix dialyzer --haly-exit-status
  - MIX_ENV=test mix exkorpion