sudo: false
branches:
  only:
    - develop
language: elixir
elixir:
  - 1.3.1
env:
  - MIX_ENV=test
otp_release:
  - 18.0
#before_script:
#  - mix dialyzer.plt 
script:
  - mix credo
  #- mix dialyzer --halt-exit-status
  - mix exkorpion