{application,exkorpion,
             [{registered,[]},
              {description,"    Test framework to help developers to write tests in a  BDD form.\n"},
              {vsn,"0.0.2-rc.2"},
              {modules,['Elixir.Exkorpion',
                        'Elixir.Exkorpion.ConsoleOutputter',
                        'Elixir.Exkorpion.Error.InvalidStructureError',
                        'Elixir.Exkorpion.Executor',
                        'Elixir.Exkorpion.ReportHandler',
                        'Elixir.Exkorpion.Server',
                        'Elixir.Mix.Tasks.Exkorpion',
                        'Elixir.Mix.Tasks.Exkorpion.Cover',
                        'Elixir.Mix.Tasks.Exkorpion.Init']},
              {applications,[kernel,stdlib,elixir,logger]}]}.